[workspace]
authors = ["suif4599 <suif4599@gmail.com>"]
channels = ["conda-forge"]
name = "MdMisc"
platforms = ["linux-64", "win-64"]
version = "0.1.0"

[pypi-options]
index-url = "https://mirrors.tuna.tsinghua.edu.cn/pypi/web/simple"


[tasks]

[dependencies]
python = "3.12.*"
fonttools = ">=4.63.0,<5"
cssutils = ">=2.15.0,<3"
pytest = ">=9.1.1,<10"
nodejs = ">=26.8.2,<26.9"

[pypi-dependencies]
jsbeautifier = ">=1.15.4, <2"
